# Generated by Django 5.2.6 on 2025-09-24 14:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(default='available', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_session', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='teacher',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_session', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
