# Generated by Django 5.2.6 on 2025-09-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_alter_session_student_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.CharField(choices=[('S', 'student'), ('T', 'teacher')]),
        ),
    ]
