# Generated by Django 5.2.6 on 2025-09-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_alter_userinfo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(default='available', max_length=10),
        ),
    ]
