# Generated by Django 5.2.6 on 2025-09-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_alter_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('scheduled', 'scheduled'), ('completed', 'completed')], default='available', max_length=10),
        ),
    ]
